# Generated by Django 4.2.5 on 2023-09-21 01:13

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('slug', models.SlugField(auto_created=True, default='<django.db.models.fields.charfield>', unique=True)),
                ('blog_id', models.UUIDField(auto_created=True, default=uuid.UUID('cf34e7e6-0a9f-4f5a-b4c1-ead73dfdb5c8'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=140)),
                ('description', models.TextField()),
                ('created_at', models.DateField(default=datetime.datetime(2023, 9, 21, 8, 13, 47, 453230))),
                ('updated_at', models.DateField(default=datetime.datetime(2023, 9, 21, 8, 13, 47, 453230))),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('posted_at', models.DateField(default=datetime.datetime(2023, 9, 21, 8, 13, 47, 453230))),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_api.blog')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.UUIDField(auto_created=True, default=uuid.UUID('a7ad4c21-c761-4c55-8f9c-22025d03e741'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('category_title', models.CharField(max_length=55)),
                ('created_at', models.DateField(default=datetime.datetime(2023, 9, 21, 8, 13, 47, 453230))),
                ('updated_at', models.DateField(default=datetime.datetime(2023, 9, 21, 8, 13, 47, 453230))),
                ('blogs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_api.blog')),
            ],
        ),
    ]
